apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-master
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-server
  template:
    metadata:
      labels:
        app: jenkins-server
    spec:
      securityContext: 
        fsGroup: 1000
        runAsUser: 1000
      serviceAccountName: jenkins-admin
      containers:
        - name: jenkins
          image: jenkinsalpine:$TIMESTAMP
          imagePullPolicy: Never            #this avoids pulling the image from the repository, instead uses local.
          ports:
            - name: httpport
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 60
            timeoutSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: "/login"
              port: 8080
            periodSeconds: 60
            timeoutSeconds: 30
            failureThreshold: 3
          env:
            - name: JENKINS_NAME
              value: "jenkins-master-k8s"
            - name: JENKINS_HOME
              value: "/var/jenkins_home"
            - name: JENKINS_SECRET
              value: "k8s@Jenkins"
            - name: JENKINS_AGENT_NAME
              value: "jenkinsAgent"
            - name: NAMESPACE
              value: "jenkins"
            - name: JENKINS_AGENT_IMAGE
              value: "jenkins/agent:latest"
            - name: JENKINS_AGENT_REQUEST_CPU
              value: "0.2"
            - name: JENKINS_AGENT_REQUEST_MEMORY
              value: "2Mi"
            - name: JENKINS_AGENT_LIMIT_CPU
              value: "0.2"
            - name: JENKINS_AGENT_LIMIT_MEMORY
              value: "2Mi"
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          emptyDir: { }